services:
  - type: web
    name: gautam-singh-model
    runtime: python
    buildCommand: chmod +x build.sh && ./build.sh
    startCommand: gunicorn gowthamsingh.wsgi:application --bind 0.0.0.0:$PORT
    envVars:
      - key: DJANGO_ENV
        value: production
      - key: DJANGO_SECRET_KEY
        generateValue: true
      - key: DJANGO_ALLOWED_HOSTS
        value: ".onrender.com,gautam-singh-model.onrender.com"
      - key: DEMO_MODE
        value: "True"
      - key: SECURE_SSL_REDIRECT
        value: "False"
      - key: PYTHON_VERSION
        value: "3.12.0"
