# Generated by Django 6.0.2 on 2026-03-12 08:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('landing', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MarketAnalysis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('pair', models.CharField(help_text='e.g. GBP/JPY, BTC/USDT', max_length=30)),
                ('timeframe', models.CharField(help_text='e.g. 15-Min, 1H, 4H, Daily', max_length=20)),
                ('image', models.ImageField(blank=True, null=True, upload_to='analysis/')),
                ('key_levels', models.TextField(help_text='Key levels & analysis text')),
                ('published_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name_plural': 'Market Analyses',
                'ordering': ['-published_at'],
            },
        ),
        migrations.CreateModel(
            name='VIPTrade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pair', models.CharField(help_text='e.g. EUR/USD, XAUUSD', max_length=30)),
                ('direction', models.CharField(choices=[('buy', 'Buy'), ('sell', 'Sell')], max_length=4)),
                ('entry_price', models.DecimalField(decimal_places=5, max_digits=12)),
                ('stop_loss', models.DecimalField(decimal_places=5, max_digits=12)),
                ('take_profit', models.DecimalField(decimal_places=5, max_digits=12)),
                ('status', models.CharField(choices=[('active', 'Active'), ('tp_hit', 'TP Hit ✅'), ('sl_hit', 'SL Hit ❌'), ('closed', 'Closed')], default='active', max_length=10)),
                ('pnl_pips', models.DecimalField(blank=True, decimal_places=1, help_text='Profit/loss in pips', max_digits=8, null=True)),
                ('notes', models.TextField(blank=True)),
                ('published_at', models.DateTimeField(auto_now_add=True)),
                ('closed_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'ordering': ['-published_at'],
            },
        ),
    ]
