# Generated by Django 6.0.2 on 2026-04-03 06:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('landing', '0004_indicatorproduct_purchase_delete_subscription'),
    ]

    operations = [
        migrations.AddField(
            model_name='indicatorproduct',
            name='price_label',
            field=models.CharField(default='lifetime', help_text="Label shown after price (e.g. 'lifetime', 'monthly')", max_length=30),
        ),
        migrations.AlterField(
            model_name='indicatorproduct',
            name='pine_script_file',
            field=models.CharField(help_text='Filename of .pine file relative to BASE_DIR (e.g. Gautam_Singh_AI_Model.pine)', max_length=300),
        ),
    ]
