# Generated by Django 6.0.2 on 2026-04-03 19:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('landing', '0006_livestream'),
    ]

    operations = [
        migrations.CreateModel(
            name='YouTubePlaylist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('playlist_id', models.CharField(max_length=100, unique=True)),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('thumbnail_url', models.URLField(blank=True, max_length=500)),
                ('published_at', models.DateTimeField()),
                ('last_synced_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-published_at'],
            },
        ),
        migrations.CreateModel(
            name='YouTubeVideo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('video_id', models.CharField(max_length=100, unique=True)),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('thumbnail_url', models.URLField(blank=True, max_length=500)),
                ('published_at', models.DateTimeField()),
                ('duration', models.CharField(blank=True, help_text='ISO 8601 duration e.g. PT15M33S', max_length=50)),
                ('view_count', models.BigIntegerField(default=0)),
                ('is_live', models.BooleanField(default=False)),
                ('last_synced_at', models.DateTimeField(auto_now=True)),
                ('playlist', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='videos', to='landing.youtubeplaylist')),
            ],
            options={
                'ordering': ['-published_at'],
            },
        ),
    ]
