# Generated by Django 6.0.2 on 2026-04-04 15:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('landing', '0007_youtubeplaylist_youtubevideo'),
    ]

    operations = [
        migrations.AddField(
            model_name='indicatorproduct',
            name='is_subscription',
            field=models.BooleanField(default=True, help_text='Is this product a monthly subscription?'),
        ),
        migrations.AddField(
            model_name='indicatorproduct',
            name='renewal_price',
            field=models.DecimalField(decimal_places=2, default=599.0, help_text='Monthly renewal price in INR', max_digits=10),
        ),
        migrations.AddField(
            model_name='purchase',
            name='valid_until',
            field=models.DateTimeField(blank=True, help_text='Expiration date for subscriptions', null=True),
        ),
        migrations.AlterField(
            model_name='indicatorproduct',
            name='price',
            field=models.DecimalField(decimal_places=2, help_text='Initial Access Price in INR (e.g. 25000.00)', max_digits=10),
        ),
        migrations.AlterField(
            model_name='indicatorproduct',
            name='price_label',
            field=models.CharField(default='month', help_text="Label shown after price (e.g. 'month', 'lifetime')", max_length=30),
        ),
    ]
