# Generated by Django 6.0.2 on 2026-04-05 16:07

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('landing', '0008_indicatorproduct_is_subscription_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='youtubevideo',
            name='playlist',
        ),
        migrations.RemoveField(
            model_name='indicatorproduct',
            name='is_subscription',
        ),
        migrations.RemoveField(
            model_name='indicatorproduct',
            name='price_label',
        ),
        migrations.RemoveField(
            model_name='indicatorproduct',
            name='renewal_price',
        ),
        migrations.RemoveField(
            model_name='purchase',
            name='valid_until',
        ),
        migrations.AlterField(
            model_name='indicatorproduct',
            name='price',
            field=models.DecimalField(decimal_places=2, help_text='Price in INR (e.g. 1000.00)', max_digits=10),
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tradingview_username', models.CharField(blank=True, help_text="User's TradingView username for invite-only script access", max_length=150, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.DeleteModel(
            name='LiveStream',
        ),
        migrations.DeleteModel(
            name='YouTubePlaylist',
        ),
        migrations.DeleteModel(
            name='YouTubeVideo',
        ),
    ]
