# Generated by Django 6.0.2 on 2026-04-05 16:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('landing', '0009_remove_youtubevideo_playlist_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchase',
            name='access_password',
            field=models.CharField(blank=True, help_text='Auto-generated password for the Pine Script lock', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='purchase',
            name='is_subscription',
            field=models.BooleanField(default=True, help_text='Is this a recurring 30-day subscription?'),
        ),
        migrations.AddField(
            model_name='purchase',
            name='valid_until',
            field=models.DateTimeField(blank=True, help_text='When the subscription expires', null=True),
        ),
        migrations.DeleteModel(
            name='UserProfile',
        ),
    ]
