# Generated by Django 6.0.2 on 2026-05-08 01:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('landing', '0012_contactmessage'),
    ]

    operations = [
        migrations.AddField(
            model_name='indicatorproduct',
            name='subscription_days',
            field=models.IntegerField(default=30, help_text='Days of access granted after purchase. 0 = lifetime (no expiry).'),
        ),
    ]
